# data_graph_ofat.yaml
# OFAT configuration for data graph generation
# Default values are used for baseline
# In vary, only one variable changes at a time, while the others remain fixed at their default values

default:
  vertices: 20000
  avg_degree: 12
  label_count: 200
  degree_distribution: ER
  label_distribution: uniform

# vary:
#   vertices: [5000, 10000, 20000, 50000, 100000]
#   avg_degree: [4, 8, 12, 16, 20]
#   label_count: [50, 100, 200, 500, 1000]
#   degree_distribution: [power-law, ER, R-MAT]
#   label_distribution: [uniform, Zipf, degree-correlated]

vary:
  vertices: [5000, 10000, 20000, 50000]
  avg_degree: [4, 8, 12, 16, 20]
  label_count: [50, 100, 200, 500]
  degree_distribution: [power-law, ER, R-MAT]
  label_distribution: [uniform, Zipf, degree-correlated]